### ISSUE TITLE
Warning: precompile directive when installing Revise v3.9.0 on Julia 1.12.0-rc2

### ISSUE THREAD

**Issue by nhz2** [timholy/Revise.jl#956]
I get a warning when I add this package in 1.12.0-rc2

Here is the full warning:

```julia-repl
julia> versioninfo()
Julia Version 1.12.0-rc2
Commit 72cbf019d04 (2025-09-06 12:00 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 9800X3D 8-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver5)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)

(@v1.12) pkg> st
Status `~/.julia/environments/v1.12/Project.toml` (empty project)

(@v1.12) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`

(@v1.12) pkg> add Revise
   Resolving package versions...
    Updating `~/.julia/environments/v1.12/Project.toml`
  [295af30f] + Revise v3.9.0
    Updating `~/.julia/environments/v1.12/Manifest.toml`
  [da1fd8a2] + CodeTracking v2.0.0
  [807dbc54] + Compiler v0.1.1
  [aa1ae85d] + JuliaInterpreter v0.10.5
  [6f1432cf] + LoweredCodeUtils v3.4.3
  [bac558e1] + OrderedCollections v1.8.1
  [ae029012] + Requires v1.3.1
  [295af30f] + Revise v3.9.0
  [56f22d72] + Artifacts v1.11.0
  [2a0f44e3] + Base64 v1.11.0
  [7b1f6079] + FileWatching v1.11.0
  [b77e0a4c] + InteractiveUtils v1.11.0
  [ac6e5ff7] + JuliaSyntaxHighlighting v1.12.0
  [76f85450] + LibGit2 v1.11.0
  [8f399da3] + Libdl v1.11.0
  [d6f4376e] + Markdown v1.11.0
  [ca575930] + NetworkOptions v1.3.0
  [de0858da] + Printf v1.11.0
  [3fa0cd96] + REPL v1.11.0
  [9a3f8284] + Random v1.11.0
  [ea8e919c] + SHA v0.7.0
  [6462fe0b] + Sockets v1.11.0
  [f489334b] + StyledStrings v1.11.0
  [cf7118a7] + UUIDs v1.11.0
  [4ec0a83e] + Unicode v1.11.0
  [e37daf67] + LibGit2_jll v1.9.0+0
  [29816b5a] + LibSSH2_jll v1.11.3+1
  [458c3c95] + OpenSSL_jll v3.5.1+0
Precompiling packages finished.
  7 dependencies successfully precompiled in 10 seconds. 14 already precompiled.
  1 dependency had output during precompilation:
┌ Revise
│  ┌ Warning: precompile directive
│  │     precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:skip_include,), Tuple{Bool}}}, typeof(methods_by_execution!), Compiled, MI, Module, Expr})
│  │ failed. Please report an issue in Revise (after checking for duplicates) or remove this directive.
│  └ @ Revise ~/.julia/packages/Revise/PSzoa/src/precompile.jl:65
└  
```

**Comment by hz-xiaxz** [comment]
Possibly related to the `Any` argument introduced in https://github.com/JuliaLang/julia/pull/57776 ?

**Comment by timholy** [comment]
Fixed in [9e3fd08](https://github.com/timholy/Revise.jl/pull/894/commits/9e3fd08b4849ba2b76617a55399424f7a2ebd47d) but currently that's only on the unmerged #894

**Comment by cossio** [comment]
FWIW, I'm seeing this warning now, in the released Julia v1.12.

**Comment by AronT-TLV** [comment]
Still seeing it in Julia 1.12.3+0.aarch64.apple.darwin14 which I just installed

**Comment by 3f6a** [comment]
@aviatesk Just want to confirm whether closing this was intentional ? #894 is not yet merged, and I am still seeing this warning today.

**Comment by aviatesk** [comment]
It's fixed by #984 .
